language: generic
notifications:
  email: false
sudo: required # Run in a container
services:
  - docker # Enable running docker commands
env:
  global:
  # Use the values from Travis directly instead of retrieving from git
  - DEP_VERSION=$TRAVIS_TAG
  - DEP_BRANCH=$TRAVIS_BRANCH
script:
- make generate
before_deploy:
- openssl aes-256-cbc -K $encrypted_1f8198cff0f3_key -iv $encrypted_1f8198cff0f3_iv -in script/travis.deploy.pem.enc -out script/travis.deploy.pem -d
- chmod 600 script/travis.deploy.pem
- eval "$(ssh-agent -s)" && ssh-add script/travis.deploy.pem
deploy:
- provider: script
  script: make publish
  on:
    repo: carolynvs/depdocs
    # Deploy the master branch and all tags
    condition: $TRAVIS_BRANCH == "master" || -n $TRAVIS_TAG
