language: generic
sudo: false # Run in a container
services:
  - docker # Enable running docker commands
env:
  # Use the values from Travis directly instead of retrieving from git
  - DEP_VERSION=$TRAVIS_TAG
  - DEP_BRANCH=$TRAVIS_BRANCH
script:
- make generate
#before_deploy:
#- openssl aes-256-cbc -K $encrypted_79d16d43cbac_key -iv $encrypted_79d16d43cbac_iv -in script/travis.deploy.pem.enc -out script/travis.deploy.pem -d
#- chmod 600 script/travis.deploy.pem
#- eval "$(ssh-agent -s)" && ssh-add script/travis.deploy.pem
deploy:
- provider: script
  script: make publish
  skip_cleanup: true
  on:
    repo: carolynvs/depdocs
    branch: master
    tags: true
