languageCode = "en-us"
title = "dep"
baseurl = "https://carolynvs.github.io/depdocs/"
theme = "hugo-alabaster-theme"

[params]
  depver = ""

[params.sidebar]
  logo = "images/logo.png"
  show_relations = false

[[menu.releases]]
    name = "v0.4.0"
    pre = "<i class='fa fa-heart'></i>"
    weight = 0
    identifier = "v0.4.0"
    url = "/releases/v0.4.0/"
[[menu.releases]]
    name = "v0.5.0"
    pre = "<i class='fa fa-heart'></i>"
    weight = 0
    identifier = "v0.5.0"
    url = "/releases/v0.5.0/"
