languageCode = "en-us"
title = "dep"
baseurl = "https://carolynvs.github.io/depdocs/"
theme = "hugo-alabaster-theme"

[params]
  depver = ""

[params.sidebar]
  logo = "images/logo.png"
  show_relations = false
